#! /bin/sh
### BEGIN INIT INFO
# Provides:          vhc
# Short-Description: Create a project ready to work
# Description:       Creating the necessary directories.
#		             Create a virtual host.
#                    Create netbeans project
### END INIT INFO

# Author: Shilov Vasilly <web36m@yandex.ru>

USER=web36m # owner
DIR=/home/www/ # directory for all projects
mkdir $DIR$1 # host directory
mkdir $DIR$1/public # directory with the working version
mkdir $DIR$1/logs # directory for logs
mkdir $DIR$1/nbp # netbeans project
mkdir $DIR$1/sources # project directory
mkdir $DIR$1/tmp # temp directory
mkdir $DIR$1/nbp/nbproject
### BEGIN CREATE NETBEANS PROJECT
mkdir $DIR$1/nbp/nbproject/private
echo > $DIR$1/nbp/nbproject/project.xml '<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://www.netbeans.org/ns/project/1">
    <type>org.netbeans.modules.php.project</type>
    <configuration>
        <data xmlns="http://www.netbeans.org/ns/php-project/1">
            <name>'$1'</name>
        </data>
    </configuration>
</project>
'
echo > $DIR$1/nbp/nbproject/project.properties 'include.path=${php.global.include.path}
php.version=PHP_53
source.encoding=UTF-8
src.dir=../sources
tags.asp=false
tags.short=true
web.root=.
'
echo > $DIR$1/nbp/nbproject/private/private.properties 'copy.src.files=true
copy.src.target='$DIR$1'/public
index.file=
run.as=LOCAL
url=http://'$1'/
'
echo > $DIR$1/nbp/nbproject/private/private.xml '<?xml version="1.0" encoding="UTF-8"?>
<project-private xmlns="http://www.netbeans.org/ns/project-private/1">
    <editor-bookmarks xmlns="http://www.netbeans.org/ns/editor-bookmarks/2" lastBookmarkId="0"/>
</project-private>
'
### END CREATE NETBEANS PROJECT
chmod -R 0755 $DIR$1 # set access rights
chown -R $USER $DIR$1 # set owner
echo > $DIR$1/sources/nginx.conf 'server {
	listen  80;
	charset utf-8;
	server_name '$1' www.'$1';
	root   '$DIR$1'/public;
	index  index.php index.html index.htm;
	access_log '$DIR$1'/logs/access.log;
	error_log '$DIR$1'/logs/error.log;
	location / {
		root '$DIR$1'/public;
		index index.php index.html index.htm;
		rewrite ^(.*)$ /index.php last;
	}
	location ~* \.php$ {
		fastcgi_pass        unix:/tmp/phpfpm.sock;
		fastcgi_index       index.php;
		fastcgi_param       SCRIPT_FILENAME  '$DIR$1'/public$fastcgi_script_name;
		include             fastcgi_params;
	}
#	location / {
#		proxy_pass http://127.0.0.1:8000;
#		proxy_set_header Host $host;
#	}
	location ~* ^/(img|js|css)/ {
		root '$DIR$1'/public;
	}
	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}
	location ~ /\.ht {
		deny  all;
	}
}' # create vhost
ln -s $DIR$1/sources/nginx.conf /etc/nginx/sites-enabled/$1 # enable vhost
echo >>/etc/hosts '127.0.0.1    '$1 # add to /etc/hosts
echo >>/etc/hosts '127.0.0.1    www.'$1 # add to /etc/hosts
/etc/init.d/nginx restart # restart nginx